### ISSUE TITLE
Glitz Radio Button Bug

### ISSUE THREAD

**Issue by Astroknut** [SpindleMonkey/project-2#1]
When I select a different radio button under Glitz, it fills in both buttons. 

Here is a screenshot: 
![screen shot 2017-08-08 at 3 17 51 pm](https://user-images.githubusercontent.com/29133938/29095093-ec94f9a0-7c4c-11e7-8a61-4de1be467fd4.png)

**Comment by SpindleMonkey** [comment]
I need to learn to type. And to test everything. The second radio button (Glitz: yes) was called 'Glita' and not 'Glitz' so it looked like a separate option.
