### ISSUE TITLE
stash form comp

### ISSUE THREAD

**Issue by enderwillsaveu** [SpindleMonkey/project-2#4]
A lot of the form inputs take in small amounts of information (ex.numbers or one word selectors) but still have inputs spanning their entire container. I think that you could re work your form to condense the amount of space it takes up which would allow users to input more quickly. Just a thought

**Comment by SpindleMonkey** [comment]
The radio button groups have moved inline, and the how much/units fields are sharing a line. The form is a few lines shorter, but I don't think shortening any of the other lines will help because they're unrelated.
